"""Edited Tweets table

Revision ID: 0087d16bb3d2
Revises: b0fc97d726ad
Create Date: 2018-04-20 18:38:17.648847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0087d16bb3d2'
down_revision = 'b0fc97d726ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tweet', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tweets_pkey')
    )
    # ### end Alembic commands ###
