"""Edited Tweets table

Revision ID: 20e7804a2b8b
Revises: cfc68fba7d7e
Create Date: 2018-04-20 17:27:54.789840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e7804a2b8b'
down_revision = 'cfc68fba7d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'tweet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('tweet', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
