"""Edited Tweets table

Revision ID: 32b10f6d945d
Revises: 20e7804a2b8b
Create Date: 2018-04-20 17:28:45.935249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b10f6d945d'
down_revision = '20e7804a2b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('tweet', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'tweet')
    # ### end Alembic commands ###
