"""Edited Tweets table

Revision ID: b0fc97d726ad
Revises: e6e2a646d91c
Create Date: 2018-04-20 17:31:14.604002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fc97d726ad'
down_revision = 'e6e2a646d91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('tweet', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'tweet')
    # ### end Alembic commands ###
