"""Delete column migration

Revision ID: cfc68fba7d7e
Revises: 
Create Date: 2018-04-20 15:31:13.568156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc68fba7d7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tweet', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='tweets_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tweets_pkey')
    )
    # ### end Alembic commands ###
