"""Edited Tweets table

Revision ID: e6e2a646d91c
Revises: 32b10f6d945d
Create Date: 2018-04-20 17:30:46.337856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e2a646d91c'
down_revision = '32b10f6d945d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'tweet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('tweet', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
